[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.124.1" # or whatever Hugo version you want

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture"

[dev]
  framework = "hugo"
  targetPort = 3000

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs]
    record = true